// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: gprc.proto

package broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyncerClient is the client API for Syncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncerClient interface {
	PassOverMessage(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Res, error)
	Broadcaster(ctx context.Context, in *Res, opts ...grpc.CallOption) (Syncer_BroadcasterClient, error)
}

type syncerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncerClient(cc grpc.ClientConnInterface) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) PassOverMessage(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/broker.Syncer/passOverMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) Broadcaster(ctx context.Context, in *Res, opts ...grpc.CallOption) (Syncer_BroadcasterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Syncer_ServiceDesc.Streams[0], "/broker.Syncer/broadcaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncerBroadcasterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Syncer_BroadcasterClient interface {
	Recv() (*Msg, error)
	grpc.ClientStream
}

type syncerBroadcasterClient struct {
	grpc.ClientStream
}

func (x *syncerBroadcasterClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncerServer is the server API for Syncer service.
// All implementations must embed UnimplementedSyncerServer
// for forward compatibility
type SyncerServer interface {
	PassOverMessage(context.Context, *Msg) (*Res, error)
	Broadcaster(*Res, Syncer_BroadcasterServer) error
	mustEmbedUnimplementedSyncerServer()
}

// UnimplementedSyncerServer must be embedded to have forward compatible implementations.
type UnimplementedSyncerServer struct {
}

func (UnimplementedSyncerServer) PassOverMessage(context.Context, *Msg) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassOverMessage not implemented")
}
func (UnimplementedSyncerServer) Broadcaster(*Res, Syncer_BroadcasterServer) error {
	return status.Errorf(codes.Unimplemented, "method Broadcaster not implemented")
}
func (UnimplementedSyncerServer) mustEmbedUnimplementedSyncerServer() {}

// UnsafeSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncerServer will
// result in compilation errors.
type UnsafeSyncerServer interface {
	mustEmbedUnimplementedSyncerServer()
}

func RegisterSyncerServer(s grpc.ServiceRegistrar, srv SyncerServer) {
	s.RegisterService(&Syncer_ServiceDesc, srv)
}

func _Syncer_PassOverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).PassOverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.Syncer/passOverMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).PassOverMessage(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_Broadcaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Res)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncerServer).Broadcaster(m, &syncerBroadcasterServer{stream})
}

type Syncer_BroadcasterServer interface {
	Send(*Msg) error
	grpc.ServerStream
}

type syncerBroadcasterServer struct {
	grpc.ServerStream
}

func (x *syncerBroadcasterServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

// Syncer_ServiceDesc is the grpc.ServiceDesc for Syncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Syncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "passOverMessage",
			Handler:    _Syncer_PassOverMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "broadcaster",
			Handler:       _Syncer_Broadcaster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gprc.proto",
}
