apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoyrate
  labels:
    app: envoyer
    type: envoyer
spec:
  replicas: 1
  selector:
    matchLabels:
      type: envoyer
  template:
    metadata:
      name: envoyrate
      labels:
        app: envoyer
        type: envoyer
    spec:
      containers:
        - name: envoy
          image: mahdizri/env
          ports:
            - containerPort: 9595
          resources:
            limits:
              memory: "8G"
              cpu: "3.8"
            requests:
              memory: "300M"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  type: ClusterIP
  ports:
    - targetPort: 9595
      port: 9000
  selector:
    app: envoyer
    type: envoyer