apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: gfn
    type: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      type: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: gfn
        type: grafana
    spec:
      containers:
        - name: grafana
          image: dockerproxy.bale.ai/grafana/grafana-enterprise
          resources:
            limits:
              memory: "500M"
              cpu: "100m"
            requests:
              memory: "400M"
              cpu: "100m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30030
  selector:
    app: gfn
    type: grafana
