
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgr
  labels:
    app: jgr
    type: jgr
spec:
  replicas: 1
  selector:
    matchLabels:
      type: jgr
  template:
    metadata:
      name: jgr
      labels:
        app: jgr
        type: jgr
    spec:
      containers:
        - name: jgr
          image: jaegertracing/all-in-one
          #resources:
            #limits:
              #memory: "700M"
              #cpu: "400m"
            #requests:
              #memory: "300M"
              #cpu: "400m"
          ports:
            - containerPort: 16686
            - containerPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jgr
spec:
  type: NodePort
  ports:
    - targetPort: 16686
      port: 16686
      nodePort: 30086
  selector:
    app: jgr
---
apiVersion: v1
kind: Service
metadata:
  name: jgrint
spec:
  type: ClusterIP
  ports:
    - targetPort: 14268
      port: 14268
  selector:
    app: jgr