apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrespg
  labels:
    app: pg
    type: databasepg
spec:
  replicas: 1
  selector:
    matchLabels:
      type: databasepg
  template:
    metadata:
      name: pg
      labels:
        app: pg
        type: databasepg
    spec:
      containers:
        - name: dbcontainerpg
          image: dockerproxy.bale.ai/dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: mahdi.zrei@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "800M"
              cpu: "2000m"
            requests:
              memory: "600M"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgrespg
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30051
  selector:
    app: pg
    type: databasepg
