apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: db
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      name: db
      labels:
        app: db
        type: database
    spec:
      containers:
        - name: dbcontainer
          image: postgres:14.1-alpine
          resources:
            limits:
              memory: "3G"
              cpu: "2"
            requests:
              memory: "1G"
              cpu: "0.8"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: db
    type: database
