apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: pmt
    type: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      type: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: pmt
        type: prometheus
    spec:
      containers:
        - name: prometheus
          image: mahdizri/prom
          resources:
            limits:
              memory: "500M"
              cpu: "100m"
            requests:
              memory: "400M"
              cpu: "100m"
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
    - targetPort: 9090
      port: 9090
  selector:
    app: pmt
    type: prometheus