
global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: broker

    static_configs:
      - targets:  ['brokermetrics1:8000', 'brokermetrics2:8000']